-- Per-list opt-outs are the recipient's own durable decision, separate from
-- list_memberships (the operator's grouping). A CSV re-import or manual re-add
-- restores the membership but can never override this record — list fan-out
-- excludes opted-out contacts at send time, mirroring the global suppressions.
CREATE TABLE list_unsubscribes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id    bigint      NOT NULL,
    contact_id bigint      NOT NULL,
    reason     varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT uk_list_unsubscribes UNIQUE (list_id, contact_id)
);
CREATE INDEX idx_list_unsub_contact ON list_unsubscribes (contact_id);
