-- Multi-tenant foundation: every signup creates a workspace; users carry a
-- role inside it (ADMIN runs the workspace, OPERATOR runs campaigns). Root
-- entities are scoped by workspace_id; child tables (mail_messages,
-- email_events, list_memberships, list_unsubscribes) isolate through their
-- parents. Provider columns are the BYO-connector selection (billing lands on
-- the tenant's own cloud account) — chosen in the console, wiring comes later.

create table workspaces (
    id               bigint generated by default as identity primary key,
    name             varchar(255) not null,
    smtp_provider    varchar(32)  not null default 'MAILHOG',
    storage_provider varchar(32)  not null default 'LOCAL',
    created_at       timestamptz(6) not null default now()
);

-- Existing single-tenant data moves into one backfill workspace so nothing breaks.
insert into workspaces (name) values ('기본 워크스페이스');

alter table users add column workspace_id bigint references workspaces (id);
alter table users add column role varchar(16) not null default 'ADMIN';
update users set workspace_id = (select min(id) from workspaces);
alter table users alter column workspace_id set not null;

alter table campaigns add column workspace_id bigint references workspaces (id);
update campaigns set workspace_id = (select min(id) from workspaces);
alter table campaigns alter column workspace_id set not null;
create index idx_campaigns_workspace on campaigns (workspace_id);

alter table contacts add column workspace_id bigint references workspaces (id);
update contacts set workspace_id = (select min(id) from workspaces);
alter table contacts alter column workspace_id set not null;
-- An address may exist once per tenant, not once globally.
alter table contacts drop constraint uk_contacts_email;
alter table contacts add constraint uk_contacts_workspace_email unique (workspace_id, email);

alter table contact_lists add column workspace_id bigint references workspaces (id);
update contact_lists set workspace_id = (select min(id) from workspaces);
alter table contact_lists alter column workspace_id set not null;
create index idx_contact_lists_workspace on contact_lists (workspace_id);

-- Templates: null workspace_id = built-in, visible to every tenant (read-only
-- besides reset); user-authored templates belong to their workspace.
alter table templates add column workspace_id bigint references workspaces (id);
update templates set workspace_id = (select min(id) from workspaces) where builtin_key is null;

-- The do-not-send decision is per tenant: unsubscribing from company A's mail
-- must not block company B's.
alter table suppressions add column workspace_id bigint references workspaces (id);
update suppressions set workspace_id = (select min(id) from workspaces);
alter table suppressions alter column workspace_id set not null;
alter table suppressions drop constraint uk_suppressions_email;
alter table suppressions add constraint uk_suppressions_workspace_email unique (workspace_id, email);
