-- V1: baseline schema (previously created by ddl-auto: update, now owned by Flyway).
--
-- Differences from the old Hibernate-generated schema, on purpose:
--   * long-text columns (campaigns.body, templates.html_body, contacts.attributes_json,
--     email_events.url) are TEXT instead of OID — @Lob on Postgres stored large-object
--     references, making the values unreadable in plain SQL and leaving orphaned LOs.
--   * constraint names are meaningful instead of Hibernate's random uk_* hashes.
--   * token/lookup indexes added for the tracking and event-metric queries.
--
-- Existing dev databases created by ddl-auto have OID columns and must be reset
-- (docker compose down -v) — dev data is disposable by design.

CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    display_name  varchar(255),
    created_at    timestamptz(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE campaigns (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject    varchar(255) NOT NULL,
    body       text NOT NULL,
    status     varchar(16) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    CONSTRAINT campaigns_status_check
        CHECK (status IN ('DRAFT', 'QUEUED', 'SENDING', 'COMPLETED'))
);

CREATE TABLE mail_messages (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id    bigint NOT NULL,
    recipient      varchar(255) NOT NULL,
    status         varchar(16) NOT NULL,
    attempts       integer NOT NULL,
    error_message  varchar(1000),
    unsub_token    varchar(255),
    tracking_token varchar(255),
    contact_id     bigint,
    updated_at     timestamptz(6) NOT NULL,
    CONSTRAINT mail_messages_status_check
        CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED', 'BOUNCED', 'SUPPRESSED'))
);
CREATE INDEX idx_msg_status ON mail_messages (status);
CREATE INDEX idx_msg_campaign ON mail_messages (campaign_id);
-- Public tracking/unsubscribe endpoints resolve messages by token on every hit.
CREATE INDEX idx_msg_unsub_token ON mail_messages (unsub_token);
CREATE INDEX idx_msg_tracking_token ON mail_messages (tracking_token);

CREATE TABLE suppressions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      varchar(255) NOT NULL,
    reason     varchar(255),
    created_at timestamptz(6) NOT NULL,
    CONSTRAINT uk_suppressions_email UNIQUE (email)
);

CREATE TABLE email_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  bigint NOT NULL,
    campaign_id bigint NOT NULL,
    type        varchar(16),
    url         text,
    occurred_at timestamptz(6) NOT NULL,
    CONSTRAINT email_events_type_check
        CHECK (type IN ('OPEN', 'CLICK', 'BOUNCE'))
);
-- countDistinctMessages(campaignId, type) drives the opened/clicked metrics.
CREATE INDEX idx_event_campaign_type ON email_events (campaign_id, type);

CREATE TABLE templates (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(255) NOT NULL,
    subject    varchar(255) NOT NULL,
    html_body  text NOT NULL,
    created_at timestamptz(6) NOT NULL,
    updated_at timestamptz(6) NOT NULL
);

CREATE TABLE contacts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           varchar(255) NOT NULL,
    first_name      varchar(255),
    last_name       varchar(255),
    attributes_json text,
    created_at      timestamptz(6) NOT NULL,
    CONSTRAINT uk_contacts_email UNIQUE (email)
);

CREATE TABLE contact_lists (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description varchar(255),
    created_at  timestamptz(6) NOT NULL
);

CREATE TABLE list_memberships (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id    bigint NOT NULL,
    contact_id bigint NOT NULL,
    CONSTRAINT uk_list_memberships UNIQUE (list_id, contact_id)
);
