-- PG 연동(토스페이먼츠 빌링키 정기결제) — BILLING-policy 8절 ③, 첫 매출 경로.
-- 빌링키: 카드 등록 시 발급받아 워크스페이스에 보관(카드번호는 우리 DB에 없다 —
-- PG가 보관하고 우리는 키로 결제만 요청). 결제 시도는 성공/실패 모두 payments 에
-- 기록한다 — 매출 원장이자 분쟁 대응 근거.
alter table workspaces add column billing_key varchar(255);

create table payments (
    id            bigint generated by default as identity primary key,
    workspace_id  bigint not null references workspaces (id),
    order_id      varchar(64) not null unique,     -- 멱등키 겸 PG 대사(reconciliation) 키
    plan          varchar(16) not null,            -- 결제 대상 플랜
    amount_krw    integer not null,
    status        varchar(16) not null
        constraint chk_payments_status check (status in ('APPROVED', 'FAILED')),
    payment_key   varchar(64),                     -- PG 측 결제 식별자 (성공 시)
    fail_reason   text,
    created_at    timestamptz(6) not null default now()
);
create index idx_payments_workspace on payments (workspace_id);
