-- 비밀번호 재설정 토큰 — 재설정 메일의 링크에 실리는 1회용·30분 만료 토큰.
-- used_at 이 찍히면 소진(재사용 불가). 사용자당 여러 행이 쌓일 수 있고(재요청),
-- 확인 시점엔 "미사용 + 미만료"만 유효하다.
create table password_reset_tokens (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users (id),
    token       varchar(64) not null unique,
    expires_at  timestamptz(6) not null,
    used_at     timestamptz(6),
    created_at  timestamptz(6) not null default now()
);
create index idx_password_reset_user on password_reset_tokens (user_id);
