-- 템플릿(재사용 디자인 자산)과 이메일(캠페인에 실제 쓰는 콘텐츠)의 개념 분리.
-- 이메일은 템플릿을 "불러와서"(내용 복사) 만들거나 빈 문서에서 시작하고,
-- 캠페인 등록 시 내용이 캠페인으로 스냅샷되는 것은 기존 방식 그대로다.
CREATE TABLE emails (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id       bigint       NOT NULL REFERENCES workspaces (id),
    name               varchar(255) NOT NULL,
    subject            varchar(255) NOT NULL,
    html_body          text         NOT NULL,
    source_template_id bigint,       -- 어느 템플릿에서 출발했는지 (없으면 빈 문서 시작)
    created_at         timestamptz  NOT NULL,
    updated_at         timestamptz  NOT NULL
);

CREATE INDEX idx_emails_workspace ON emails (workspace_id, updated_at DESC);
