-- 워크스페이스별 빌트인 템플릿 숨기기. 빌트인은 전역 공유 자산이라 삭제할 수
-- 없으므로(시더가 되살림), "내 목록에서만 안 보이게"를 별도 기록으로 푼다.
-- 숨겨도 이미 캠페인·이메일에 복사된 내용에는 영향이 없다.
CREATE TABLE hidden_builtin_templates (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint      NOT NULL REFERENCES workspaces (id),
    template_id  bigint      NOT NULL REFERENCES templates (id),
    created_at   timestamptz NOT NULL,
    CONSTRAINT uk_hidden_builtin UNIQUE (workspace_id, template_id)
);
