-- 콘솔 인앱 알림. 첫 소비자는 "캠페인 발송 완료" — 완료 판정의 원자적 UPDATE
-- claim(completeIfSending)에서 이긴 쪽만 1건 발행하므로 중복 알림이 없다.
CREATE TABLE notifications (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint       NOT NULL REFERENCES workspaces (id),
    type         varchar(32)  NOT NULL,
    title        varchar(255) NOT NULL,
    campaign_id  bigint,       -- 클릭 시 이동할 캠페인 (소프트 참조)
    created_at   timestamptz  NOT NULL,
    read_at      timestamptz   -- null = 안 읽음
);

CREATE INDEX idx_notifications_workspace ON notifications (workspace_id, created_at DESC);
