-- 플랫폼 운영자 — 워크스페이스 ADMIN/OPERATOR(테넌트 안의 역할)와 별개인, 테넌트를
-- 넘나드는 운영 권한. 정지/해제·플랜 조정·캠페인 중단을 psql 대신 콘솔(/ops)에서 한다.
-- 초기 지정은 APP_PLATFORM_OPERATORS 환경변수의 이메일 목록을 기동 시 시드한다.
ALTER TABLE users ADD COLUMN platform_role varchar(16);

-- 운영자 행위 감사 로그 — /api/ops/** 는 테넌트 격리(by-id 404)의 의도적 예외라서
-- 모든 변경을 누가·언제·어느 테넌트에 했는지 남긴다. 조회는 최신순.
CREATE TABLE platform_audit_log (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email  varchar(255) NOT NULL,
    action       varchar(48)  NOT NULL,   -- SUSPEND | UNSUSPEND | CHANGE_PLAN | REVOKE_API_KEY | ABORT_CAMPAIGN
    workspace_id bigint,                   -- 소프트 참조 (테넌트가 지워져도 기록은 남는다)
    campaign_id  bigint,
    detail       varchar(500),             -- 사유·이전값→새값
    created_at   timestamptz  NOT NULL
);

CREATE INDEX idx_platform_audit_created ON platform_audit_log (created_at DESC);
