package io.github.ahrimjang.mail.core.service;

import java.util.List;

/**
 * Canonical content of the built-in (example) templates. The boot seeder
 * inserts any missing seed as a template row (keyed by {@code key}), and
 * "원본 복원" rewrites an edited built-in back to this content. This class is
 * the single source of truth — the console renders whatever is in the DB.
 *
 * <p>Every seed is a BLOCK-editor document: an {@code <!--opblocks:...-->}
 * marker (the editor's block model, base64 JSON) followed by the email-safe
 * rendered HTML. The marker routes the console to the box editor, so users
 * edit these with drag-and-drop blocks instead of raw HTML — much safer for
 * non-technical users. Generated with the frontend serializer
 * (blocksToHtmlBody in frontend/src/outpace/blocks.ts); regenerate there if
 * the designs change.
 */
public final class BuiltinTemplates {

    /** One seed: key is stable and unique; name/subject/body are the original content. */
    public record Seed(String key, String name, String subject, String htmlBody) {
    }

    public static final List<Seed> ALL = List.of(
            new Seed("newsletter", "월간 뉴스레터", "{{name}}님, 7월의 Acme 소식을 전해요", """
                    <!--opblocks:eyJ2IjoyLCJibG9ja3MiOlt7ImlkIjoiYmkwMDAwIiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoiIiwiYm9keSI6IjxiPkFDTUUgTU9OVEhMWSDCtyA37JuU7Zi4PC9iPiIsImFsaWduIjoibGVmdCIsImJnIjoiIzI1NjNlYiIsImNvbG9yIjoiI2JmZGJmZSIsImZvbnRTaXplIjoxMiwicGFkWSI6MjZ9LHsiaWQiOiJiaTAwMDEiLCJ0eXBlIjoidGV4dCIsImhlYWRpbmciOiIiLCJib2R5IjoiPGI+7J2067KIIOuLrCwg64aT7LmY66m0IOyVhOyJrOyatCDshozsi508L2I+IiwiYWxpZ24iOiJsZWZ0IiwiYmciOiIjMjU2M2ViIiwiY29sb3IiOiIjZmZmZmZmIiwiZm9udFNpemUiOjI4LCJwYWRZIjowfSx7ImlkIjoiYmkwMDAyIiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoiIiwiYm9keSI6IuyDiCDquLDriqUgMuqwgOyngOyZgCDqtazrj4XsnpAg7KCE7JqpIO2YnO2DneydhCDri7TslZjslrTsmpQiLCJhbGlnbiI6ImxlZnQiLCJiZyI6IiMyNTYzZWIiLCJjb2xvciI6IiNiZmRiZmUiLCJmb250U2l6ZSI6MTQsInBhZFkiOjE4fSx7ImlkIjoiYmkwMDAzIiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoiIiwiYm9keSI6IuyViOuFle2VmOyEuOyalCB7e25hbWV9feuLmCDwn5GLPGJyPuydtOuyiCDri6zrj4QgQWNtZeyZgCDtlajqu5jtlbQg7KO87IWU7IScIOqwkOyCrO2VtOyalC4g67CU7IGcIOu2hOuTpOydhCDsnITtlbQg7ZW17Ius66eMIOqzqOudvCDsoJXrpqztlojsirXri4jri6QuIiwiYWxpZ24iOiJsZWZ0IiwiYmciOiIjZmZmZmZmIiwiZm9udFNpemUiOjE1LCJwYWRZIjoyNn0seyJpZCI6ImJpMDAwNCIsInR5cGUiOiJkaXZpZGVyIiwiYmciOiIjZmZmZmZmIn0seyJpZCI6ImJpMDAwNSIsInR5cGUiOiJ0ZXh0IiwiaGVhZGluZyI6IuKRoCDsmIjslb0g67Cc7Iah7J20IOyDneqyvOyWtOyalCIsImJvZHkiOiLsuqDtjpjsnbjsnYQg7JuQ7ZWY64qUIOyLnOqwgeyXkCDsnpDrj5nsnLzroZwg67Cc7Iah7ZWp64uI64ukLiDstpzqt7zquLggOOyLnCwg7KCQ7IusIDEy7IucIOKAlCDsl7TrnozrpaDsnbQg6rCA7J6lIOuGkuydgCDsi5zqsITsnYQg6rOo6528IOyYiOyVve2VtCDrs7TshLjsmpQuIiwiYWxpZ24iOiJsZWZ0IiwiYmciOiIjZmZmZmZmIiwicGFkWSI6MTZ9LHsiaWQiOiJiaTAwMDYiLCJ0eXBlIjoidGV4dCIsImhlYWRpbmciOiLikaEg6rWs64+F7J6QIOyghOyaqSDtmJztg50iLCJib2R5Ijoi7J20IOuplOydvOydhCDrsJvsnLzsi6Ag67aE6ruY66eMIDxiPu2UhOumrOuvuOyXhCDtlIzrnpwgMeqwnOyblCDrrLTro4w8L2I+IOy/oO2PsOydhCDrk5zroKTsmpQuIOyVhOuemCDrsoTtirzsnYQg64iE66W066m0IOqzhOygleyXkCDrsJTroZwg7KCB7Jqp65Cp64uI64ukLiIsImFsaWduIjoibGVmdCIsImJnIjoiI2ZmZmZmZiIsInBhZFkiOjE2fSx7ImlkIjoiYmkwMDA3IiwidHlwZSI6ImJ1dHRvbiIsImxhYmVsIjoi7J2067KIIOuLrCDshozsi50g7KCE7LK0IOuztOq4sCIsInVybCI6Imh0dHBzOi8vZXhhbXBsZS5jb20vbmV3cyIsImFsaWduIjoiY2VudGVyIiwiYmciOiIjZmZmZmZmIiwiYnRuQ29sb3IiOiIjMjU2M2ViIn0seyJpZCI6ImJpMDAwOCIsInR5cGUiOiJ0ZXh0IiwiaGVhZGluZyI6IiIsImJvZHkiOiLri6TsnYwg7Zi4IOyYiOqzoCDigJQg7YG066at66Wg7J2EIDLrsLDroZwg7Jis66awIOyekOuPme2ZlCDsi5zrgpjrpqzsmKTrpbwg6rO16rCc7ZWp64uI64ukLiIsImFsaWduIjoiY2VudGVyIiwiYmciOiIjZmZmZmZmIiwiZm9udFNpemUiOjEyLCJjb2xvciI6IiNhMWExYWEiLCJwYWRZIjo4fSx7ImlkIjoiYmkwMDA5IiwidHlwZSI6ImZvb3RlciIsInRleHQiOiJBY21lIEluYy4gwrcg7ISc7Jq47Yq567OE7IucIOqwleuCqOq1rCDthYztl6TrnoDroZwgMTIzIMK3IOusuOydmCBzdXBwb3J0QGFjbWUuaW8iLCJiZyI6IiNmNGY0ZjUifV19-->
                    <table width="600" align="center" cellpadding="0" cellspacing="0" style="font-family:sans-serif;background:#ffffff">
                      <tr><td style="padding:26px 34px;background-color:#2563eb;text-align:left"><p style="margin:0;font-size:12px;color:#bfdbfe;line-height:1.75"><b>ACME MONTHLY · 7월호</b></p></td></tr>
                      <tr><td style="padding:0px 34px;background-color:#2563eb;text-align:left"><p style="margin:0;font-size:28px;color:#ffffff;line-height:1.75"><b>이번 달, 놓치면 아쉬운 소식</b></p></td></tr>
                      <tr><td style="padding:18px 34px;background-color:#2563eb;text-align:left"><p style="margin:0;font-size:14px;color:#bfdbfe;line-height:1.75">새 기능 2가지와 구독자 전용 혜택을 담았어요</p></td></tr>
                      <tr><td style="padding:26px 34px;background-color:#ffffff;text-align:left"><p style="margin:0;font-size:15px;color:#3f3f46;line-height:1.75">안녕하세요 {{name}}님 👋<br>이번 달도 Acme와 함께해 주셔서 감사해요. 바쁜 분들을 위해 핵심만 골라 정리했습니다.</p></td></tr>
                      <tr><td style="padding:8px 34px;background-color:#ffffff"><hr style="border:none;border-top:1px solid #e4e4e7;margin:0"></td></tr>
                      <tr><td style="padding:16px 34px;background-color:#ffffff;text-align:left"><h2 style="margin:0 0 12px;font-size:22px;letter-spacing:-0.02em;color:#18181b">① 예약 발송이 생겼어요</h2><p style="margin:0;font-size:14.5px;color:#3f3f46;line-height:1.75">캠페인을 원하는 시각에 자동으로 발송합니다. 출근길 8시, 점심 12시 — 열람률이 가장 높은 시간을 골라 예약해 보세요.</p></td></tr>
                      <tr><td style="padding:16px 34px;background-color:#ffffff;text-align:left"><h2 style="margin:0 0 12px;font-size:22px;letter-spacing:-0.02em;color:#18181b">② 구독자 전용 혜택</h2><p style="margin:0;font-size:14.5px;color:#3f3f46;line-height:1.75">이 메일을 받으신 분께만 <b>프리미엄 플랜 1개월 무료</b> 쿠폰을 드려요. 아래 버튼을 누르면 계정에 바로 적용됩니다.</p></td></tr>
                      <tr><td style="padding:22px 34px;background-color:#ffffff;text-align:center"><a href="https://example.com/news" style="display:inline-block;background:#2563eb;color:#ffffff;font-size:14.5px;font-weight:bold;padding:13px 32px;border-radius:10px;text-decoration:none">이번 달 소식 전체 보기</a></td></tr>
                      <tr><td style="padding:8px 34px;background-color:#ffffff;text-align:center"><p style="margin:0;font-size:12px;color:#a1a1aa;line-height:1.75">다음 호 예고 — 클릭률을 2배로 올린 자동화 시나리오를 공개합니다.</p></td></tr>
                      <tr><td style="padding:24px 34px;background-color:#f4f4f5;text-align:center"><p style="margin:0;font-size:12px;color:#a1a1aa;line-height:1.75">Acme Inc. · 서울특별시 강남구 테헤란로 123 · 문의 support@acme.io</p></td></tr>
                    </table>"""),

            new Seed("promo", "프로모션 · 할인 안내", "{{name}}님만을 위한 주말 특별 할인", """
                    <!--opblocks:eyJ2IjoyLCJibG9ja3MiOlt7ImlkIjoiYmkwMDBhIiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoiIiwiYm9keSI6IjxiPldFRUtFTkQgT05MWTwvYj4iLCJhbGlnbiI6ImNlbnRlciIsImJnIjoiI2Q5NzcwNiIsImNvbG9yIjoiI2ZkZTY4YSIsImZvbnRTaXplIjoxMiwicGFkWSI6MjZ9LHsiaWQiOiJiaTAwMGIiLCJ0eXBlIjoidGV4dCIsImhlYWRpbmciOiIiLCJib2R5IjoiPGI+7LWc64yAIDQwJSDtlaDsnbg8L2I+IiwiYWxpZ24iOiJjZW50ZXIiLCJiZyI6IiNkOTc3MDYiLCJjb2xvciI6IiNmZmZmZmYiLCJmb250U2l6ZSI6MjgsInBhZFkiOjB9LHsiaWQiOiJiaTAwMGMiLCJ0eXBlIjoidGV4dCIsImhlYWRpbmciOiIiLCJib2R5Ijoi7J287JqU7J28IOyekOygleq5jOyngCDCtyDsoIQg7IOB7ZKIIOyggeyaqSIsImFsaWduIjoiY2VudGVyIiwiYmciOiIjZDk3NzA2IiwiY29sb3IiOiIjZmRlNjhhIiwiZm9udFNpemUiOjE0LCJwYWRZIjoxOH0seyJpZCI6ImJpMDAwZCIsInR5cGUiOiJ0ZXh0IiwiaGVhZGluZyI6IiIsImJvZHkiOiJ7e25hbWV9feuLmCwg7J2067KIIOyjvOunkOq5jOyngOunjCDrk5zrpqzripQg7Zic7YOd7J207JeQ7JqULjxicj7snqXrsJTqtazri4jsl5Ag64u07JWE65GQ7IugIOyDge2SiOuPhCDsnbTrr7gg7ZWg7J246rCA66GcIOuwlOuAjOyWtCDsnojslrTsmpQuIiwiYWxpZ24iOiJjZW50ZXIiLCJiZyI6IiNmZmZmZmYiLCJmb250U2l6ZSI6MTUsInBhZFkiOjI2fSx7ImlkIjoiYmkwMDBlIiwidHlwZSI6InR3byIsImxlZnRUaXRsZSI6IuyLnOymjCDsmKTtlIQg7LWc64yAIDQwJSIsImxlZnRCb2R5Ijoi7Jes66aEIOyLnOymjCDsoIQg7IOB7ZKI7J20IOuMgOyDgeydtOyXkOyalC4g7J246riwIOyCrOydtOymiOuKlCDquIjrsKkg7ZKI7KCI65CY64uIIOyEnOuRkOultOyEuOyalC4iLCJyaWdodFRpdGxlIjoi7KCEIOqxtCDrrLTro4wg67Cw7IahIiwicmlnaHRCb2R5Ijoi6riI7JWhIOyhsOqxtCDsl4bsnbQsIOyjvOunkCDrj5nslYgg7KO866y47ZWcIOuqqOuToCDqsbTsnYQg66y066OM66GcIOuztOuCtOuTnOugpOyalC4iLCJiZyI6IiNmZmZiZWIifSx7ImlkIjoiYmkwMDBmIiwidHlwZSI6ImJ1dHRvbiIsImxhYmVsIjoi7KeA6riIIOyHvO2Vke2VmOq4sCIsInVybCI6Imh0dHBzOi8vZXhhbXBsZS5jb20vc2FsZSIsImFsaWduIjoiY2VudGVyIiwiYmciOiIjZmZmZmZmIiwiYnRuQ29sb3IiOiIjZDk3NzA2In0seyJpZCI6ImJpMDAwZyIsInR5cGUiOiJ0ZXh0IiwiaGVhZGluZyI6IiIsImJvZHkiOiLsv6Dtj7Ag7L2U65OcIDxiPldFRUtFTkQ0MDwvYj4g4oCUIOqysOygnCDsi5wg7J6F66Cl7ZWY66m0IDUlIOy2lOqwgCDtlaDsnbggKOydvOu2gCDruIzrnpzrk5wg7KCc7Jm4KSIsImFsaWduIjoiY2VudGVyIiwiYmciOiIjZmZmYmViIiwiZm9udFNpemUiOjEyLjUsImNvbG9yIjoiIzkyNDAwZSIsInBhZFkiOjEyfSx7ImlkIjoiYmkwMDBoIiwidHlwZSI6ImZvb3RlciIsInRleHQiOiJBY21lIEluYy4gwrcg7ISc7Jq47Yq567OE7IucIOqwleuCqOq1rCDthYztl6TrnoDroZwgMTIzIMK3IOusuOydmCBzdXBwb3J0QGFjbWUuaW8iLCJiZyI6IiNmNGY0ZjUifV19-->
                    <table width="600" align="center" cellpadding="0" cellspacing="0" style="font-family:sans-serif;background:#ffffff">
                      <tr><td style="padding:26px 34px;background-color:#d97706;text-align:center"><p style="margin:0;font-size:12px;color:#fde68a;line-height:1.75"><b>WEEKEND ONLY</b></p></td></tr>
                      <tr><td style="padding:0px 34px;background-color:#d97706;text-align:center"><p style="margin:0;font-size:28px;color:#ffffff;line-height:1.75"><b>최대 40% 할인</b></p></td></tr>
                      <tr><td style="padding:18px 34px;background-color:#d97706;text-align:center"><p style="margin:0;font-size:14px;color:#fde68a;line-height:1.75">일요일 자정까지 · 전 상품 적용</p></td></tr>
                      <tr><td style="padding:26px 34px;background-color:#ffffff;text-align:center"><p style="margin:0;font-size:15px;color:#3f3f46;line-height:1.75">{{name}}님, 이번 주말까지만 드리는 혜택이에요.<br>장바구니에 담아두신 상품도 이미 할인가로 바뀌어 있어요.</p></td></tr>
                      <tr><td style="padding:22px 34px;background-color:#fffbeb"><table width="100%" cellpadding="0" cellspacing="0"><tr><td width="48%" valign="top"><h3 style="margin:0 0 6px;font-size:14px;color:#18181b">시즌 오프 최대 40%</h3><p style="margin:0;font-size:13px;color:#71717a;line-height:1.6">여름 시즌 전 상품이 대상이에요. 인기 사이즈는 금방 품절되니 서두르세요.</p></td><td width="4%"></td><td width="48%" valign="top"><h3 style="margin:0 0 6px;font-size:14px;color:#18181b">전 건 무료 배송</h3><p style="margin:0;font-size:13px;color:#71717a;line-height:1.6">금액 조건 없이, 주말 동안 주문한 모든 건을 무료로 보내드려요.</p></td></tr></table></td></tr>
                      <tr><td style="padding:22px 34px;background-color:#ffffff;text-align:center"><a href="https://example.com/sale" style="display:inline-block;background:#d97706;color:#ffffff;font-size:14.5px;font-weight:bold;padding:13px 32px;border-radius:10px;text-decoration:none">지금 쇼핑하기</a></td></tr>
                      <tr><td style="padding:12px 34px;background-color:#fffbeb;text-align:center"><p style="margin:0;font-size:12.5px;color:#92400e;line-height:1.75">쿠폰 코드 <b>WEEKEND40</b> — 결제 시 입력하면 5% 추가 할인 (일부 브랜드 제외)</p></td></tr>
                      <tr><td style="padding:24px 34px;background-color:#f4f4f5;text-align:center"><p style="margin:0;font-size:12px;color:#a1a1aa;line-height:1.75">Acme Inc. · 서울특별시 강남구 테헤란로 123 · 문의 support@acme.io</p></td></tr>
                    </table>"""),

            new Seed("welcome", "신규 가입 환영", "{{name}}님, 환영합니다! 시작을 도와드릴게요", """
                    <!--opblocks:eyJ2IjoyLCJibG9ja3MiOlt7ImlkIjoiYmkwMDBpIiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoi7ZmY7JiB7ZWp64uI64ukIPCfjokiLCJib2R5Ijoie3tuYW1lfX3ri5gsIO2VqOq7mO2VmOqyjCDrkJjslrQg6riw67uQ7JqULjxicj7rlLEgM+u2hOydtOuptCDspIDruYTqsIAg64Gd64KY7JqULiIsImFsaWduIjoiY2VudGVyIiwiYmciOiIjZmZmZmZmIiwiZm9udFNpemUiOjE1LCJwYWRZIjozNH0seyJpZCI6ImJpMDAwaiIsInR5cGUiOiJ0ZXh0IiwiaGVhZGluZyI6IiIsImJvZHkiOiI8Yj5TVEVQIDEg4oCUIO2UhOuhnO2VhCDsmYTshLHtlZjquLA8L2I+PGJyPuq0gOyLrOyCrOulvCDslYzroKTso7zsi5zrqbQg7LaU7LKc7J20IO2bqOyUrCDsoJXtmZXtlbTsoLjsmpQuIiwiYWxpZ24iOiJsZWZ0IiwiYmciOiIjZjBmZGY0IiwicGFkWSI6MTZ9LHsiaWQiOiJiaTAwMGsiLCJ0eXBlIjoidGV4dCIsImhlYWRpbmciOiIiLCJib2R5IjoiPGI+U1RFUCAyIOKAlCDqtIDsi6wg7KO87KCcIOq1rOuPhe2VmOq4sDwvYj48YnI+66ek7KO8IOyblOyalOydvCDslYTsuagsIOunnuy2pCDsmpTslb3snYQg66mU7J2866GcIOuztOuCtOuTnOugpOyalC4iLCJhbGlnbiI6ImxlZnQiLCJiZyI6IiNmMGZkZjQiLCJwYWRZIjoxNn0seyJpZCI6ImJpMDAwbCIsInR5cGUiOiJ0ZXh0IiwiaGVhZGluZyI6IiIsImJvZHkiOiI8Yj5TVEVQIDMg4oCUIOybsOy7tCDsv6Dtj7Ag7IKs7Jqp7ZWY6riwPC9iPjxicj7ssqsg7KO866y4IDxiPjE1JSDtlaDsnbg8L2I+IOy/oO2PsOydtCDsnbTrr7gg6rOE7KCV7JeQIOuTpOyWtOyeiOyWtOyalC4iLCJhbGlnbiI6ImxlZnQiLCJiZyI6IiNmMGZkZjQiLCJwYWRZIjoxNn0seyJpZCI6ImJpMDAwbSIsInR5cGUiOiJidXR0b24iLCJsYWJlbCI6IjPrtoQg66eM7JeQIOyLnOyeke2VmOq4sCIsInVybCI6Imh0dHBzOi8vZXhhbXBsZS5jb20vc3RhcnQiLCJhbGlnbiI6ImNlbnRlciIsImJnIjoiI2ZmZmZmZiIsImJ0bkNvbG9yIjoiIzE2YTM0YSJ9LHsiaWQiOiJiaTAwMG4iLCJ0eXBlIjoidGV4dCIsImhlYWRpbmciOiIiLCJib2R5Ijoi6raB6riI7ZWcIOygkOydtCDsnojsnLzrqbQg7J20IOuplOydvOyXkCDqt7jrg6Ug64u17J6l7ZW0IOyjvOyEuOyalC4g7KeE7KecIOyCrOuejOydtCDri7Xtlanri4jri6QuIiwiYWxpZ24iOiJjZW50ZXIiLCJiZyI6IiNmZmZmZmYiLCJmb250U2l6ZSI6MTIsImNvbG9yIjoiI2ExYTFhYSIsInBhZFkiOjh9LHsiaWQiOiJiaTAwMG8iLCJ0eXBlIjoiZm9vdGVyIiwidGV4dCI6IkFjbWUgSW5jLiDCtyDshJzsmrjtirnrs4Tsi5wg6rCV64Ko6rWsIO2FjO2XpOuegOuhnCAxMjMgwrcg66y47J2YIHN1cHBvcnRAYWNtZS5pbyIsImJnIjoiI2Y0ZjRmNSJ9XX0=-->
                    <table width="600" align="center" cellpadding="0" cellspacing="0" style="font-family:sans-serif;background:#ffffff">
                      <tr><td style="padding:34px 34px;background-color:#ffffff;text-align:center"><h2 style="margin:0 0 12px;font-size:22px;letter-spacing:-0.02em;color:#18181b">환영합니다 🎉</h2><p style="margin:0;font-size:15px;color:#3f3f46;line-height:1.75">{{name}}님, 함께하게 되어 기뻐요.<br>딱 3분이면 준비가 끝나요.</p></td></tr>
                      <tr><td style="padding:16px 34px;background-color:#f0fdf4;text-align:left"><p style="margin:0;font-size:14.5px;color:#3f3f46;line-height:1.75"><b>STEP 1 — 프로필 완성하기</b><br>관심사를 알려주시면 추천이 훨씬 정확해져요.</p></td></tr>
                      <tr><td style="padding:16px 34px;background-color:#f0fdf4;text-align:left"><p style="margin:0;font-size:14.5px;color:#3f3f46;line-height:1.75"><b>STEP 2 — 관심 주제 구독하기</b><br>매주 월요일 아침, 맞춤 요약을 메일로 보내드려요.</p></td></tr>
                      <tr><td style="padding:16px 34px;background-color:#f0fdf4;text-align:left"><p style="margin:0;font-size:14.5px;color:#3f3f46;line-height:1.75"><b>STEP 3 — 웰컴 쿠폰 사용하기</b><br>첫 주문 <b>15% 할인</b> 쿠폰이 이미 계정에 들어있어요.</p></td></tr>
                      <tr><td style="padding:22px 34px;background-color:#ffffff;text-align:center"><a href="https://example.com/start" style="display:inline-block;background:#16a34a;color:#ffffff;font-size:14.5px;font-weight:bold;padding:13px 32px;border-radius:10px;text-decoration:none">3분 만에 시작하기</a></td></tr>
                      <tr><td style="padding:8px 34px;background-color:#ffffff;text-align:center"><p style="margin:0;font-size:12px;color:#a1a1aa;line-height:1.75">궁금한 점이 있으면 이 메일에 그냥 답장해 주세요. 진짜 사람이 답합니다.</p></td></tr>
                      <tr><td style="padding:24px 34px;background-color:#f4f4f5;text-align:center"><p style="margin:0;font-size:12px;color:#a1a1aa;line-height:1.75">Acme Inc. · 서울특별시 강남구 테헤란로 123 · 문의 support@acme.io</p></td></tr>
                    </table>"""),

            new Seed("repurchase", "재구매 유도", "{{name}}님, 취향에 맞춰 골라봤어요", """
                    <!--opblocks:eyJ2IjoyLCJibG9ja3MiOlt7ImlkIjoiYmkwMDBwIiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoie3tuYW1lfX3ri5gsIOyYpOuenOunjOydtOyXkOyalCDimJUiLCJib2R5Ijoi66eI7KeA66eJIOyjvOusuCDsnbTtm4Qg7IOI66GcIOuTpOyWtOyYqCDqsoPrk6Qg7KSR7JeQ7IScPGJyPnt7bmFtZX1964uYIOy3qO2WpeyXkCDrp57snYQg66eM7ZWcIOuRkCDqsIDsp4Drpbwg6rOo656Q7Ja07JqULiIsImFsaWduIjoibGVmdCIsImJnIjoiI2ZmZmZmZiIsImZvbnRTaXplIjoxNSwicGFkWSI6Mjh9LHsiaWQiOiJiaTAwMHEiLCJ0eXBlIjoidHdvIiwibGVmdFRpdGxlIjoi7Iuc6re464uI7LKYIOu4lOugjOuTnCDsm5DrkZAiLCJsZWZ0Qm9keSI6IuuLpOyLnCDssYTsm4zrkZgg65WM6rCAIOuQkOyWtOyalC4g7KCV6riwIOq1rOuPheycvOuhnCDrsJTqvrjrqbQgPGI+MTUlIO2VoOyduDwvYj7sl5Ag67Cw7Iah67mE64+EIOustOujjOyYiOyalC4gPGEgaHJlZj1cImh0dHBzOi8vZXhhbXBsZS5jb20vaXRlbTFcIj7rs7Trn6wg6rCA6riwPC9hPiIsInJpZ2h0VGl0bGUiOiLsi6DsoJztkogg65Oc66as7Y28IOyEuO2KuCIsInJpZ2h0Qm9keSI6IuydtOuyiCDri6wg7Lac7IucLCDrpqzrt7Ag7Y+J7KCQIDxiPjQuOTwvYj4uIO2ZiOy5tO2OmCDsnoXrrLgg7IS47Yq466GcIOqwgOyepSDrp47snbQg7ISg7YOd64+87JqULiA8YSBocmVmPVwiaHR0cHM6Ly9leGFtcGxlLmNvbS9pdGVtMlwiPuuztOufrCDqsIDquLA8L2E+IiwiYmciOiIjZWZmNmZmIn0seyJpZCI6ImJpMDAwciIsInR5cGUiOiJkaXZpZGVyIiwiYmciOiIjZmZmZmZmIn0seyJpZCI6ImJpMDAwcyIsInR5cGUiOiJ0ZXh0IiwiaGVhZGluZyI6IiIsImJvZHkiOiLsp4Drgpwg7KO866y4IOyjvOq4sOuhnCDrs7TrqbQg7JuQ65GQ6rCAIOydtOuyiCDso7zsr6Qg65ao7Ja07KeIIOyLnOq4sOyYiOyalC4g7J6s7KO866y47J2AIOuyhO2KvCDtlZwg67KI7J2066m0IOuBneuCmOyalC4iLCJhbGlnbiI6ImxlZnQiLCJiZyI6IiNmZmZmZmYiLCJmb250U2l6ZSI6MTMuNSwiY29sb3IiOiIjNzE3MTdhIiwicGFkWSI6MTJ9LHsiaWQiOiJiaTAwMHQiLCJ0eXBlIjoiYnV0dG9uIiwibGFiZWwiOiLstpTsspwg7IOB7ZKIIOyghOyytCDrs7TquLAiLCJ1cmwiOiJodHRwczovL2V4YW1wbGUuY29tL3JlY29tbWVuZCIsImFsaWduIjoibGVmdCIsImJnIjoiI2ZmZmZmZiIsImJ0bkNvbG9yIjoiIzI1NjNlYiJ9LHsiaWQiOiJiaTAwMHUiLCJ0eXBlIjoiZm9vdGVyIiwidGV4dCI6IkFjbWUgSW5jLiDCtyDshJzsmrjtirnrs4Tsi5wg6rCV64Ko6rWsIO2FjO2XpOuegOuhnCAxMjMgwrcg66y47J2YIHN1cHBvcnRAYWNtZS5pbyIsImJnIjoiI2Y0ZjRmNSJ9XX0=-->
                    <table width="600" align="center" cellpadding="0" cellspacing="0" style="font-family:sans-serif;background:#ffffff">
                      <tr><td style="padding:28px 34px;background-color:#ffffff;text-align:left"><h2 style="margin:0 0 12px;font-size:22px;letter-spacing:-0.02em;color:#18181b">{{name}}님, 오랜만이에요 ☕</h2><p style="margin:0;font-size:15px;color:#3f3f46;line-height:1.75">마지막 주문 이후 새로 들어온 것들 중에서<br>{{name}}님 취향에 맞을 만한 두 가지를 골랐어요.</p></td></tr>
                      <tr><td style="padding:22px 34px;background-color:#eff6ff"><table width="100%" cellpadding="0" cellspacing="0"><tr><td width="48%" valign="top"><h3 style="margin:0 0 6px;font-size:14px;color:#18181b">시그니처 블렌드 원두</h3><p style="margin:0;font-size:13px;color:#71717a;line-height:1.6">다시 채워둘 때가 됐어요. 정기 구독으로 바꾸면 <b>15% 할인</b>에 배송비도 무료예요. <a href="https://example.com/item1">보러 가기</a></p></td><td width="4%"></td><td width="48%" valign="top"><h3 style="margin:0 0 6px;font-size:14px;color:#18181b">신제품 드리퍼 세트</h3><p style="margin:0;font-size:13px;color:#71717a;line-height:1.6">이번 달 출시, 리뷰 평점 <b>4.9</b>. 홈카페 입문 세트로 가장 많이 선택돼요. <a href="https://example.com/item2">보러 가기</a></p></td></tr></table></td></tr>
                      <tr><td style="padding:8px 34px;background-color:#ffffff"><hr style="border:none;border-top:1px solid #e4e4e7;margin:0"></td></tr>
                      <tr><td style="padding:12px 34px;background-color:#ffffff;text-align:left"><p style="margin:0;font-size:13.5px;color:#71717a;line-height:1.75">지난 주문 주기로 보면 원두가 이번 주쯤 떨어질 시기예요. 재주문은 버튼 한 번이면 끝나요.</p></td></tr>
                      <tr><td style="padding:22px 34px;background-color:#ffffff;text-align:left"><a href="https://example.com/recommend" style="display:inline-block;background:#2563eb;color:#ffffff;font-size:14.5px;font-weight:bold;padding:13px 32px;border-radius:10px;text-decoration:none">추천 상품 전체 보기</a></td></tr>
                      <tr><td style="padding:24px 34px;background-color:#f4f4f5;text-align:center"><p style="margin:0;font-size:12px;color:#a1a1aa;line-height:1.75">Acme Inc. · 서울특별시 강남구 테헤란로 123 · 문의 support@acme.io</p></td></tr>
                    </table>"""),

            new Seed("receipt", "주문 영수증", "주문이 확인되었습니다 (#{{orderNo}})", """
                    <!--opblocks:eyJ2IjoyLCJibG9ja3MiOlt7ImlkIjoiYmkwMDB2IiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoi7KO866y47ZW0IOyjvOyFlOyEnCDqsJDsgqztlanri4jri6QiLCJib2R5Ijoie3tuYW1lfX3ri5jsnZgg7KO866y4IDxiPiN7e29yZGVyTm99fTwvYj7qsIAg7KCV7IOBIOygkeyImOuQmOyXiOyKteuLiOuLpC48YnI+67O07Ya1IDF+MuydvCDslYjsl5Ag67Cc7Iah64+87JqULiIsImFsaWduIjoibGVmdCIsImJnIjoiI2ZmZmZmZiIsInBhZFkiOjI2fSx7ImlkIjoiYmkwMDB3IiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoiIiwiYm9keSI6IjxiPuyjvOusuCDrgrTsl608L2I+IiwiYWxpZ24iOiJsZWZ0IiwiYmciOiIjZjRmNGY1IiwiZm9udFNpemUiOjEyLjUsImNvbG9yIjoiIzcxNzE3YSIsInBhZFkiOjEwfSx7ImlkIjoiYmkwMDB4IiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoiIiwiYm9keSI6IuyLnOq3uOuLiOyymCDruJTroIzrk5wg7JuQ65GQIDUwMGcgw5cgMiDigJQgPGI+MzYsMDAw7JuQPC9iPjxicj7tlbjrk5wg65Oc66as7Y28IOyEuO2KuCDDlyAxIOKAlCA8Yj4yOSwwMDDsm5A8L2I+PGJyPuuwsOyGoeu5hCDigJQgPGI+66y066OMPC9iPiIsImFsaWduIjoibGVmdCIsImJnIjoiI2ZmZmZmZiIsImZvbnRTaXplIjoxNCwicGFkWSI6MTZ9LHsiaWQiOiJiaTAwMHkiLCJ0eXBlIjoiZGl2aWRlciIsImJnIjoiI2ZmZmZmZiJ9LHsiaWQiOiJiaTAwMHoiLCJ0eXBlIjoidGV4dCIsImhlYWRpbmciOiIiLCJib2R5Ijoi7ZWp6rOEIDxiPjY1LDAwMOybkDwvYj4iLCJhbGlnbiI6InJpZ2h0IiwiYmciOiIjZmZmZmZmIiwiZm9udFNpemUiOjE2LCJjb2xvciI6IiMxODE4MWIiLCJwYWRZIjoxMH0seyJpZCI6ImJpMDAxMCIsInR5cGUiOiJ0ZXh0IiwiaGVhZGluZyI6IiIsImJvZHkiOiI8Yj7rsLDshqHsp4A8L2I+PGJyPnt7YWRkcmVzc319PGJyPjxicj48Yj7rsLDshqEg7JWI64K0PC9iPjxicj7rsJzshqHsnbQg7Iuc7J6R65CY66m0IOusuOyekOuhnCDshqHsnqUg67KI7Zi466W8IOuztOuCtOuTnOugpOyalC4iLCJhbGlnbiI6ImxlZnQiLCJiZyI6IiNmNGY0ZjUiLCJmb250U2l6ZSI6MTMsInBhZFkiOjE2fSx7ImlkIjoiYmkwMDExIiwidHlwZSI6InRleHQiLCJoZWFkaW5nIjoiIiwiYm9keSI6IuuzuCDrqZTsnbzsnYAg67Cc7IugIOyghOyaqeyeheuLiOuLpC4g7KO866y4IOuzgOqyvcK37Leo7IaM64qUIDxhIGhyZWY9XCJodHRwczovL2V4YW1wbGUuY29tL29yZGVyc1wiPuyjvOusuCDrgrTsl60g7Y6Y7J207KeAPC9hPuyXkOyEnCDrsJTroZwg7ZWgIOyImCDsnojslrTsmpQuIiwiYWxpZ24iOiJsZWZ0IiwiYmciOiIjZmZmZmZmIiwiZm9udFNpemUiOjEyLCJjb2xvciI6IiNhMWExYWEiLCJwYWRZIjoxMH0seyJpZCI6ImJpMDAxMiIsInR5cGUiOiJmb290ZXIiLCJ0ZXh0IjoiQWNtZSBJbmMuIMK3IOyEnOyauO2KueuzhOyLnCDqsJXrgqjqtawg7YWM7Zek656A66GcIDEyMyDCtyDrrLjsnZggc3VwcG9ydEBhY21lLmlvIiwiYmciOiIjZjRmNGY1In1dfQ==-->
                    <table width="600" align="center" cellpadding="0" cellspacing="0" style="font-family:sans-serif;background:#ffffff">
                      <tr><td style="padding:26px 34px;background-color:#ffffff;text-align:left"><h2 style="margin:0 0 12px;font-size:22px;letter-spacing:-0.02em;color:#18181b">주문해 주셔서 감사합니다</h2><p style="margin:0;font-size:14.5px;color:#3f3f46;line-height:1.75">{{name}}님의 주문 <b>#{{orderNo}}</b>가 정상 접수되었습니다.<br>보통 1~2일 안에 발송돼요.</p></td></tr>
                      <tr><td style="padding:10px 34px;background-color:#f4f4f5;text-align:left"><p style="margin:0;font-size:12.5px;color:#71717a;line-height:1.75"><b>주문 내역</b></p></td></tr>
                      <tr><td style="padding:16px 34px;background-color:#ffffff;text-align:left"><p style="margin:0;font-size:14px;color:#3f3f46;line-height:1.75">시그니처 블렌드 원두 500g × 2 — <b>36,000원</b><br>핸드 드리퍼 세트 × 1 — <b>29,000원</b><br>배송비 — <b>무료</b></p></td></tr>
                      <tr><td style="padding:8px 34px;background-color:#ffffff"><hr style="border:none;border-top:1px solid #e4e4e7;margin:0"></td></tr>
                      <tr><td style="padding:10px 34px;background-color:#ffffff;text-align:right"><p style="margin:0;font-size:16px;color:#18181b;line-height:1.75">합계 <b>65,000원</b></p></td></tr>
                      <tr><td style="padding:16px 34px;background-color:#f4f4f5;text-align:left"><p style="margin:0;font-size:13px;color:#3f3f46;line-height:1.75"><b>배송지</b><br>{{address}}<br><br><b>배송 안내</b><br>발송이 시작되면 문자로 송장 번호를 보내드려요.</p></td></tr>
                      <tr><td style="padding:10px 34px;background-color:#ffffff;text-align:left"><p style="margin:0;font-size:12px;color:#a1a1aa;line-height:1.75">본 메일은 발신 전용입니다. 주문 변경·취소는 <a href="https://example.com/orders">주문 내역 페이지</a>에서 바로 할 수 있어요.</p></td></tr>
                      <tr><td style="padding:24px 34px;background-color:#f4f4f5;text-align:center"><p style="margin:0;font-size:12px;color:#a1a1aa;line-height:1.75">Acme Inc. · 서울특별시 강남구 테헤란로 123 · 문의 support@acme.io</p></td></tr>
                    </table>""")
    );

    private BuiltinTemplates() {
    }
}
